/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
operacion_1_svc(operacionBinaria *argp, struct svc_req *rqstp)
{
	static int  result;
	
	printf("Entero 1: %i\n", argp -> entero1);
	printf("Entero 2: %i\n", argp -> entero2);
	printf("Operación: %s\n", argp -> op);

	switch (argp -> op[0])
	{
		case '+':
			result = argp -> entero1 + argp -> entero2;
			break;
		case '-':
			result = argp -> entero1 - argp -> entero2;
			break;
		case '*':
			result = argp -> entero1 * argp -> entero2;
			break;
		case '/':
			result = argp -> entero1 / argp -> entero2;
			break;
		default:
			printf("Han introducido una operación no válida\n");
			result = 0;
			break;
	}

	printf("Este es el resultado que se devuelve de parte del servidor: %i\n", result);

	return &result;
}
