/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_operador (XDR *xdrs, operador *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, TAM_OP))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_operacionBinaria (XDR *xdrs, operacionBinaria *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->entero1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->entero2))
		 return FALSE;
	 if (!xdr_operador (xdrs, &objp->op))
		 return FALSE;
	return TRUE;
}
