/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hoja.h"

bool_t
xdr_registro (XDR *xdrs, registro *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nombre, MAX_NOMBRE))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, MAX_IP))
		 return FALSE;
	return TRUE;
}
