/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
operacion_1_svc(operacionBinaria *argp, struct svc_req *rqstp)
{
	static int  result;
	

	return &result;
}
