/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host, operacionBinaria operacion_1_arg)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, PRIMERA, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = operacion_1(&operacion_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	printf("Resultado devuelto: %i\n", *result_1);
}


int
main (int argc, char *argv[])
{
	char *host;
	operacionBinaria op;

	if (argc < 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	op -> entero1 = atoi(argv[2]);
	op -> entero2 = atoi(argv[4]);
	op -> op = argv[3];

	calculadora_1 (host, op);
exit (0);
}
