/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TAM_OP 1

typedef char *operador;

struct operacionBinaria {
	int entero1;
	int entero2;
	operador op;
};
typedef struct operacionBinaria operacionBinaria;

#define CALCULADORA 0x20000001
#define PRIMERA 1

#if defined(__STDC__) || defined(__cplusplus)
#define OPERACION 1
extern  int * operacion_1(operacionBinaria *, CLIENT *);
extern  int * operacion_1_svc(operacionBinaria *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OPERACION 1
extern  int * operacion_1();
extern  int * operacion_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operador (XDR *, operador*);
extern  bool_t xdr_operacionBinaria (XDR *, operacionBinaria*);

#else /* K&R C */
extern bool_t xdr_operador ();
extern bool_t xdr_operacionBinaria ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
