/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hoja.h"


void
hoja_1(char *host, char *operacion, registro alta_1_arg)
{
	CLIENT *clnt;
	char * *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, HOJA, PRIMERA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = baja_1(&alta_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Resultado recibido desde el servidor: %s\n", *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *operation;
	registro reg;

	if (argc < 5) {
		printf ("usage: %s server_host operation name ip\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	operation = argv[2];
	reg.nombre = argv[3];
	reg.ip = argv [4];

	hoja_1 (host, operation, reg);
exit (0);
}
